2025-01-24 14:10:32,895 INFO    MainThread:14392 [wandb_setup.py:_flush():68] Current SDK version is 0.19.1
2025-01-24 14:10:32,895 INFO    MainThread:14392 [wandb_setup.py:_flush():68] Configure stats pid to 14392
2025-01-24 14:10:32,895 INFO    MainThread:14392 [wandb_setup.py:_flush():68] Loading settings from C:\Users\Vidak\.config\wandb\settings
2025-01-24 14:10:32,895 INFO    MainThread:14392 [wandb_setup.py:_flush():68] Loading settings from D:\Exercise 2\cikm-safeultr-master\wandb\settings
2025-01-24 14:10:32,895 INFO    MainThread:14392 [wandb_setup.py:_flush():68] Loading settings from environment variables
2025-01-24 14:10:32,895 INFO    MainThread:14392 [wandb_setup.py:_flush():68] wandb: Using wandb-core as the SDK backend.  Please refer to https://wandb.me/wandb-core for more information.
2025-01-24 14:10:32,896 INFO    MainThread:14392 [wandb_setup.py:_flush():68] wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
2025-01-24 14:10:32,896 INFO    MainThread:14392 [wandb_init.py:_log_setup():528] Logging user logs to D:\Exercise 2\cikm-safeultr-master\wandb\run-20250124_141032-3p9qsxkj\logs\debug.log
2025-01-24 14:10:32,896 INFO    MainThread:14392 [wandb_init.py:_log_setup():529] Logging internal logs to D:\Exercise 2\cikm-safeultr-master\wandb\run-20250124_141032-3p9qsxkj\logs\debug-internal.log
2025-01-24 14:10:32,896 INFO    MainThread:14392 [wandb_init.py:init():644] calling init triggers
2025-01-24 14:10:32,896 INFO    MainThread:14392 [wandb_init.py:init():650] wandb.init called with sweep_config: {}
config: {}
2025-01-24 14:10:32,896 INFO    MainThread:14392 [wandb_init.py:init():680] starting backend
2025-01-24 14:10:32,896 INFO    MainThread:14392 [wandb_init.py:init():684] sending inform_init request
2025-01-24 14:10:32,910 INFO    MainThread:14392 [backend.py:_multiprocessing_setup():104] multiprocessing start_methods=spawn, using: spawn
2025-01-24 14:10:32,911 INFO    MainThread:14392 [wandb_init.py:init():697] backend started and connected
2025-01-24 14:10:32,912 INFO    MainThread:14392 [wandb_init.py:init():790] updated telemetry
2025-01-24 14:10:32,946 INFO    MainThread:14392 [wandb_init.py:init():822] communicating run to backend with 90.0 second timeout
2025-01-24 14:10:33,237 ERROR   MainThread:14392 [wandb_init.py:init():849] encountered error: failed to upsert bucket: returned error 401 Unauthorized: {"errors":[{"message":"user is not logged in","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-01-24 14:10:33,237 ERROR   MainThread:14392 [wandb_init.py:init():1308] error in wandb.init()
Traceback (most recent call last):
  File "C:\Users\Vidak\miniconda3\envs\myenv\lib\site-packages\wandb\sdk\wandb_init.py", line 1298, in init
    return wi.init()
  File "C:\Users\Vidak\miniconda3\envs\myenv\lib\site-packages\wandb\sdk\wandb_init.py", line 855, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 401 Unauthorized: {"errors":[{"message":"user is not logged in","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-01-24 14:10:33,246 WARNING MsgRouterThr:14392 [router.py:message_loop():75] message_loop has been closed
